trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Run build ($(buildConfiguration))'

- script: dotnet test
  displayName: Run tests

- task: DotNetCoreCLI@2
  displayName: "Pack nuget packages"
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj;!**/*.Test.csproj'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  displayName: "Copy packages to public location"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'NuGet Packages'
    publishLocation: 'Container'
